# -*- coding: utf-8 -*-
"""store_sales_forecasting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/103lVn33cDmm7Z8f2bSorkGN479R_W_6a
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error

from google.colab import files
files.upload()

df = pd.read_csv("train.csv")
df.head()

df.info()
df.describe()

df['date'] = pd.to_datetime(df['date'])

df['year'] = df['date'].dt.year
df['month'] = df['date'].dt.month
df['day'] = df['date'].dt.day
df['dayofweek'] = df['date'].dt.dayofweek

df = df.sample(frac=0.2, random_state=42)
df_encoded = pd.get_dummies(df, columns=['family'], drop_first=True)

X = df_encoded.drop(['sales', 'date'], axis=1)
y = df_encoded['sales']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = RandomForestRegressor(
    n_estimators=50,
    random_state=42,
    n_jobs=-1
)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

mae = mean_absolute_error(y_test, y_pred)
print("Mean Absolute Error:", mae)

plt.figure(figsize=(10,5))
plt.plot(y_test.values[:100], label='Actual Sales')
plt.plot(y_pred[:100], label='Predicted Sales')
plt.legend()
plt.title("Actual vs Predicted Sales")
plt.show()